# Generated by Django 5.0.2 on 2024-02-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tele_bot_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_type_mileage',
            field=models.CharField(max_length=255, null=True, verbose_name='Тип кузова, Пробег автомобиля'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_type',
            field=models.CharField(max_length=255, null=True, verbose_name='Тип двигателя'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(max_length=255, null=True, verbose_name='Трансмиссия'),
        ),
    ]
