# Generated by Django 5.0.2 on 2024-02-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tele_bot_app', '0002_alter_car_body_type_mileage_alter_car_engine_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telegram_id', models.IntegerField(null=True, verbose_name='telegra_id')),
                ('chat_id', models.IntegerField(null=True, verbose_name='chat_id')),
                ('message', models.TextField(null=True, verbose_name='Сообщения')),
            ],
        ),
    ]
