# Generated by Django 5.0.2 on 2024-02-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tele_bot_app', '0003_message_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message_data',
            name='telegram_id',
            field=models.IntegerField(null=True, verbose_name='telegram_id'),
        ),
    ]
