# Generated by Django 5.0.2 on 2024-02-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tele_bot_app', '0004_alter_message_data_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price_USD',
            field=models.IntegerField(null=True, verbose_name='Цена в долларах'),
        ),
    ]
