# Generated by Django 5.0.2 on 2024-02-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tele_bot_app', '0006_rename_price_byn_car_price_byn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(null=True, verbose_name='Объём в литрах'),
        ),
    ]
