# Generated by Django 5.0.2 on 2024-02-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tele_bot_app', '0007_alter_car_engine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AlterModelOptions(
            name='message_data',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AddField(
            model_name='message_data',
            name='full_date_time',
            field=models.DateTimeField(null=True, verbose_name='Дата и время получения'),
        ),
    ]
