# Generated by Django 5.0.2 on 2024-03-01 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tele_bot_app', '0008_alter_car_options_alter_message_data_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message_data',
            new_name='TelegramMessage',
        ),
    ]
