# Generated by Django 5.0.2 on 2024-03-01 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tele_bot_app', '0009_rename_message_data_telegrammessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TelegramMessage',
            new_name='Message_data',
        ),
    ]
