# Generated by Django 5.0.2 on 2024-03-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tele_bot_app', '0012_alter_message_data_options_alter_messagedata_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='http_link',
            field=models.URLField(null=True, verbose_name='Ссылка'),
        ),
    ]
