# Generated by Django 5.0.2 on 2024-03-01 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tele_bot_app', '0013_alter_car_http_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['price_usd'], 'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
    ]
