# Generated by Django 5.0.2 on 2024-03-04 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tele_bot_app', '0014_alter_car_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageData',
        ),
    ]
