# Generated by Django 5.0.3 on 2024-03-07 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tele_bot_app', '0015_delete_messagedata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message_data',
            new_name='MessageData',
        ),
    ]
