# Generated by Django 5.0.3 on 2024-03-08 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tele_bot_app', '0016_rename_message_data_messagedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telegram_id', models.IntegerField(null=True, verbose_name='telegram_id')),
                ('chat_id', models.IntegerField(null=True, verbose_name='chat_id')),
                ('message', models.TextField(null=True, verbose_name='Сообщения')),
                ('full_date_time', models.DateTimeField(null=True, verbose_name='Дата и время получения')),
                ('messagedata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tele_bot_app.messagedata')),
            ],
            options={
                'verbose_name': 'Отправленное сообщение',
                'verbose_name_plural': 'Отправленные сообщения',
            },
        ),
    ]
