# Generated by Django 5.0.3 on 2024-03-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tele_bot_app', '0017_sentmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentmessage',
            name='full_date_time',
            field=models.DateTimeField(null=True, verbose_name='Дата и время отправления'),
        ),
    ]
