# Generated by Django 5.0.3 on 2024-03-10 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tele_bot_app', '0018_alter_sentmessage_full_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentmessage',
            name='messagedata',
        ),
    ]
