# Generated by Django 5.0.3 on 2024-03-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tele_bot_app', '0020_alter_sentmessage_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypingMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('typing_message', models.TextField(null=True, verbose_name='Сообщения')),
            ],
        ),
        migrations.AlterField(
            model_name='sentmessage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
