# Generated by Django 5.0.3 on 2024-03-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tele_bot_app', '0022_alter_messagedata_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagedata',
            name='chat_id',
            field=models.PositiveBigIntegerField(null=True, verbose_name='chat_id'),
        ),
    ]
