# Generated by Django 5.0.3 on 2024-03-11 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tele_bot_app', '0023_alter_messagedata_chat_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SentMessage',
        ),
    ]
