# Generated by Django 5.0.3 on 2024-03-11 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tele_bot_app', '0024_delete_sentmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TypingMessage',
        ),
    ]
