# Generated by Django 5.0.3 on 2024-03-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tele_bot_app', '0026_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telegram_id', models.PositiveBigIntegerField(null=True, verbose_name='telegram_id')),
                ('message', models.TextField(null=True, verbose_name='Сообщения')),
                ('sentmessage_time', models.DateTimeField(null=True, verbose_name='Дата и время отправления')),
            ],
            options={
                'verbose_name': 'Отправленное сообщение',
                'verbose_name_plural': 'Отправленные сообщения',
                'ordering': ('sentmessage_time',),
            },
        ),
        migrations.AlterModelOptions(
            name='messagedata',
            options={'ordering': ('full_date_time',), 'verbose_name': 'Полученное сообщение', 'verbose_name_plural': 'Полученные сообщения'},
        ),
    ]
