# Generated by Django 5.0.3 on 2024-03-14 18:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tele_bot_app', '0027_sentmessage_alter_messagedata_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagedata',
            name='full_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время получения'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время отправления'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Отметка об отправлении'),
        ),
        migrations.AlterField(
            model_name='sentmessage',
            name='sentmessage_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время отправления'),
        ),
    ]
