# Generated by Django 5.0.3 on 2024-03-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tele_bot_app', '0028_alter_messagedata_full_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentmessage',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='Отметка об отправлении'),
        ),
    ]
